# Generated by Django 3.2.5 on 2021-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('main_topping', models.CharField(default='ser', max_length=40)),
                ('size', models.CharField(choices=[('S', 'mała'), ('M', 'średnia'), ('L', 'duża'), ('XXL', 'ogromna')], default='S', max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
